[env]
TERM = "xterm-256color"

# enable_scroll_bar = true

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 13

[colors]
primary = { background = "#1E2326", foreground = "#DCD7BA" }
normal = { black = "#090618", red = "#C34043", green = "#76946A", blue = "#7E9CD8", yellow = "#C0A36E", magenta = "#957FB8", cyan = "#6A9589", white = "#C8C093" }
bright = { black = "#727169", red = "#E82424", green = "#98BB6C", blue = "#7FB4CA", yellow = "#E6C384", magenta = "#938AA9", cyan = "#7AA89F", white = "#DCD7BA" }
